<?php
echo '<!DOCTYPE html>';
echo '<html lang="en">';
echo '<head>';
echo '<meta charset="UTF-8">';
echo '<meta name="viewport" content="width=device-width, initial-scale=1.0">';
echo '<title>Document</title>';
echo '<link rel="stylesheet" href="reset.css">';
echo '<link rel="stylesheet" href="CSS/navStyle.css">';
echo '</head>';
echo '<body>';
echo '<!-- Navigation links -->';
echo '<div class="topnav">';
echo '<a href="index.php" >Home Page</a>';
echo '<a href="Car Care.php" >Car Care</a>';
echo '<a href="Detailing.php" >Detailing</a>';
echo '<a href="locations.php" >Locations</a>';
echo '<a href="about-us.php" >About Us</a>';
echo '<a href="bookNow.php" >Book Now</a>';
echo '';
echo '<div class="topnav-right">';
echo '<a href="#membership.php" >Membership</a>';
echo '';
echo '</div>';
echo '</div>';
echo '<!--image attribute-->';
echo '<img src="images/LC500.png" alt="LC 500">';
echo '<h1>Expert Car Detailing: From Luxury Brands To Your Everyday Ride In Nairobi</h1>';
echo '<p>';
echo '</body>';
echo '</html>';
?>